"""Quantify the effect of treating gloss self-loops as cycles in compute_kernel.

OEWN glosses frequently repeat the headword ("a violin is a ... violin ..."),
producing ``u -> u`` self-loops in the paper-wordnet definition digraph. Before
commit 7d12e64 ``compute_kernel`` excluded self-loops when counting out-degree,
so a self-loop-only word looked like a dead-end and was stripped from the Kernel
(taking its acyclic upstream with it). This script:

  1. counts the self-loops in the paper-wordnet graph,
  2. recomputes the Kernel/Core/Satellite/seed decomposition for each seed
     method with the *current* (fixed) ``compute_kernel``,
  3. re-runs it against a self-loop-free copy of the graph to recover the
     *pre-fix* numbers, and
  4. writes a comparison to ``reports/self-loop-fix-impact.{md,json}``.

Run:  uv run python scripts/self_loop_fix_impact.py [--lexicon oewn:2024]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from meanings.graph_analysis import Adjacency, analyze_kernel
from meanings.wordnet_pipeline import build_paper_wordnet_graph

SEED_METHODS = ("bounded-scc", "exact-small-greedy", "exact-cutting")


def strip_self_loops(adjacency: Adjacency) -> Adjacency:
    return {u: {t for t in ts if t != u} for u, ts in adjacency.items()}


def summarize(nodes: set[str], adjacency: Adjacency, seed_method: str) -> dict:
    ka = analyze_kernel(nodes, adjacency, seed_method=seed_method, core_policy="source-union")
    return {
        "seed_method": seed_method,
        "kernel_node_count": len(ka.kernel_nodes),
        "core_node_count": len(ka.core_nodes),
        "satellite_node_count": len(ka.satellite_nodes),
        "seed_node_count": len(ka.seed_nodes),
        "kernel_scc_count": len(ka.kernel_sccs),
        "source_scc_count": len(ka.source_sccs),
        "residual_cyclic_scc_count": ka.residual_cyclic_scc_count,
        "minset_exact": ka.minset_result.exact,
        "layers_computed": len(ka.layer_by_node) > 0,
        "layer_histogram_buckets": len(ka.layer_histogram),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lexicon", default="oewn:2024")
    parser.add_argument("--out-md", default="reports/self-loop-fix-impact.md")
    parser.add_argument("--out-json", default="reports/self-loop-fix-impact.json")
    args = parser.parse_args()

    build = build_paper_wordnet_graph(args.lexicon)
    adjacency: Adjacency = build.adjacency
    nodes = set(adjacency)
    self_loops = sorted(u for u, ts in adjacency.items() if u in ts)

    no_loops = strip_self_loops(adjacency)
    report = {
        "lexicon": args.lexicon,
        "node_count": len(nodes),
        "edge_count": sum(len(ts) for ts in adjacency.values()),
        "self_loop_count": len(self_loops),
        "self_loop_examples": self_loops[:20],
        "with_self_loops": {m: summarize(nodes, adjacency, m) for m in SEED_METHODS},
        "without_self_loops_prefix_baseline": {m: summarize(nodes, no_loops, m) for m in SEED_METHODS},
    }

    Path(args.out_json).write_text(json.dumps(report, indent=2), encoding="utf-8")

    lines = [
        "# Impact of treating gloss self-loops as cycles in `compute_kernel`",
        "",
        f"Lexicon: `{args.lexicon}` — {report['node_count']:,} nodes, "
        f"{report['edge_count']:,} edges, **{report['self_loop_count']:,} self-loops** "
        "(words that appear in their own gloss).",
        "",
        "Generated by `scripts/self_loop_fix_impact.py`. \"With self-loops\" = current "
        "(post-fix) `compute_kernel`; \"pre-fix baseline\" = same pipeline on a "
        "self-loop-free copy of the graph (reproduces the old behaviour).",
        "",
        "| seed method | variant | kernel | core | satellites | seed | kernel SCCs | source SCCs | residual cyclic SCC | layers computed |",
        "|---|---|---:|---:|---:|---:|---:|---:|---:|:--:|",
    ]
    for m in SEED_METHODS:
        for label, key in (("post-fix", "with_self_loops"),
                           ("pre-fix", "without_self_loops_prefix_baseline")):
            r = report[key][m]
            lines.append(
                f"| `{m}` | {label} | {r['kernel_node_count']:,} | {r['core_node_count']:,} | "
                f"{r['satellite_node_count']:,} | {r['seed_node_count']:,} | {r['kernel_scc_count']:,} | "
                f"{r['source_scc_count']:,} | {r['residual_cyclic_scc_count']} | "
                f"{'yes' if r['layers_computed'] else 'NO'} |"
            )
    lines += [
        "",
        "Notes:",
        "- All self-loop nodes belong in the Kernel by definition (a 1-node cycle is a "
        "forced feedback-vertex-set member); pre-fix they were silently dropped. The "
        "self-loop fix's *only* effect is the Kernel-size increase shown above (the new "
        "self-loop nodes plus the acyclic upstream that used to be stripped with them).",
        "- If `residual cyclic SCC` is non-zero for a method, `analyze_kernel` skips the "
        "layer map (`compute_layer_map`), so the layer histogram comes out empty for that "
        "method. `bounded-scc` (8-pass cap) already left a residual cycle on the "
        "*pre-fix* Kernel — that is a property of the bounded heuristic on a large Kernel, "
        "not of the self-loop fix. The fix does push `exact-cutting` (single-pass cutter) "
        "from 1 to several residual SCCs, because the larger Kernel has more big SCCs the "
        "one-shot pass cannot fully crack. `exact-small-greedy` (loops to completion) gives "
        "`residual = 0` and a full layer map both before and after.",
        "- The committed `reports/oewn-paper-wordnet-kernel-*.{md,json}` predate both this "
        "fix and the MinSet-solver refactor; regenerate via the CLI.",
        "- Example self-loop words: " + ", ".join(f"`{w}`" for w in report["self_loop_examples"][:12]) + ".",
        "",
    ]
    Path(args.out_md).write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {args.out_md} and {args.out_json}")
    print(f"self-loops: {report['self_loop_count']:,}")
    for m in SEED_METHODS:
        a = report["with_self_loops"][m]
        b = report["without_self_loops_prefix_baseline"][m]
        print(f"  {m}: kernel {b['kernel_node_count']:,} -> {a['kernel_node_count']:,}, "
              f"seed {b['seed_node_count']:,} -> {a['seed_node_count']:,}, "
              f"residual cyclic SCC {b['residual_cyclic_scc_count']} -> {a['residual_cyclic_scc_count']}, "
              f"layers {'yes' if b['layers_computed'] else 'NO'} -> {'yes' if a['layers_computed'] else 'NO'}")


if __name__ == "__main__":
    main()
